- hosts: pcs
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to latest version
      apt:
        upgrade: dist

    - name: Aktifkan IP Forwarding (permanent)
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#?net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward=1'

    - name: Terapkan konfigurasi sysctl (langsung aktif)
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Buat file info deployment
      copy:
        content: "✅ Sistem telah diupdate oleh Ansible\n"
        dest: /home/ansible/deploy-info.txt
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Tampilkan pesan sukses
      debug:
        msg: "✅ Konfigurasi berhasil dijalankan!"
