- hosts: pcs
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to latest version
      apt:
        upgrade: dist

    - name: Aktifkan IP Forwarding
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#?net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward=1'

    - name: Terapkan konfigurasi sysctl
      command: sysctl -p

    - name: Buat file info deployment
      copy:
        content: "✅ Sistem telah diupdate oleh Ansible\n"
        dest: /home/ansible/deploy-info.txt
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Tampilkan pesan sukses
      debug:
        msg: "✅ Konfigurasi berhasil dijalankan!"


